<style>
a.button {
    background: transparent url('http://www.oscaralexander.com/tutorials/img/bg_button_a.gif') no-repeat scroll top right;
    color: #444;
    display: block;
    float: left;
    font: normal 12px arial, sans-serif;
    height: 24px;
    margin-right: 6px;
    padding-right: 18px; /* sliding doors padding */
    text-decoration: none;
}

a.button span {
    background: transparent url('http://www.oscaralexander.com/tutorials/img/bg_button_span.gif') no-repeat;
    display: block;
    line-height: 14px;
    padding: 5px 0 5px 18px;
}
</style>

<?php

$title='Restaraunts';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>


<table class="table">
<tr>
	<th>Restaraunt name</th>
</tr>
<tr>
	<td><?php echo $this->escapeHtml($food->name);?></td>
</tr>
<tr>
	<td>
		<a class="button" href="<? $this->url('food',
			array('action'=>'index')); ?>"><span>Choose again</span></a>
	</td>
</tr>
<tr>
    <td>
        <iframe
          width="100%"
          height="600"
          frameborder="0" style="border:0"
          src="https://www.google.com/maps/embed/v1/place?q=<?php echo $food->lat ?>,<?php echo $food->lng ?>&key=AIzaSyB7TjXipPiHQW3UzkzlMSd9xfz_THUnkmo">
        </iframe>
    </td>
</tr>
</table>



