<?php
$title = 'Delete Room';
$this->headTitle($title);
?>
<?php if(count($this->messages)) : ?>
<ul>
    <?php foreach ($this->messages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'room',
    array(
        'action' => 'delete',
    )
));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formRow($form->get('room'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
