<?php
// module/Album/view/reservation/album/delete.phtml:

$title = 'Share reservation';
$this->headTitle($title);
?>
<?php if(count($this->messages)) : ?>
<ul>
    <?php foreach ($this->messages as $msg) : ?>
    <li><?php echo $msg; ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p> Insert the username of the person you wish to share '<?php echo $this->escapeHtml($reservation->title); ?>' with.
    
</p>
<?php
$url = $this->url('medical', array(
    'action' => 'share',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $reservation->id; ?>" />
    <input type="text" name="username" />
    <input type="submit" name="submit" value="Submit" />
</div>
</form>
