<?php

$title='Reservation';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table">
<tr>
    <th>Title</th>
    <th>Location</th>
</tr>
<tr>
    <td><?php echo $this->escapeHtml($reservation->title);?></td>
    <td><?php echo $this->escapeHtml($food->name);?></td>
</tr>
</table>

<iframe
  width="100%"
  height="600"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?q=<?php echo $food->lat ?>,<?php echo $food->lng ?>&key=AIzaSyB7TjXipPiHQW3UzkzlMSd9xfz_THUnkmo">
</iframe>

